### PR TITLE
[sc-10135] Re-build widget for nuclia.com to use ask endpoint

### PR DESCRIPTION
**Pull request by operramon**

### CODE REVIEW

**Review by mpellerin42 — COMMENTED** [review]
Why did you copy `common-style.scss` and `_global.scss`? I think those two should be reused by just referencing them where needed, no?

**Review by mpellerin42 — APPROVED** [review]
I feel like it's ok, just wondering if it's needed to duplicate `LoadingDots` as well: duplicating components that have been modified for the specificity of GolbalWidget makes sense, but any components which is just the same as the common one should not be duplicated.

**Comment by operramon** [comment]
> Why did you copy `common-style.scss` and `_global.scss`? I think those two should be reused by just referencing them where needed, no?

ah, I thought the global styles were different, but I see that they are the same.
Now it's fixed.

**Comment by operramon** [comment]
> I feel like it's ok, just wondering if it's needed to duplicate `LoadingDots` as well: duplicating components that have been modified for the specificity of GolbalWidget makes sense, but any components which is just the same as the common one should not be duplicated.

Fixed

**Review by ebrehault — APPROVED** [review]

**Pull request merged**
